import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  header: {
    width: '100%',
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: '#232526',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: 18,
    top: 50,
    zIndex: 10,
  },
  headerTitle: {
    fontSize: 32,
    color: '#fff',
    fontWeight: 'bold',
    letterSpacing: 1,
    textAlign: 'center',
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 22,
    paddingVertical: 12,
  },
  timerText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#232526',
    marginLeft: 6,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginTop: 14,
    width: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    alignSelf: 'center',
  },
  exerciseName: {
    fontSize: 20,
    fontWeight: '600',
    color: '#232526',
    textAlign: 'center',
    marginBottom: 6,
  },
  cardDivider: {
    height: 2,
    backgroundColor: '#e0e0e0',
    width: '100%',
    marginBottom: 8,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: 6,
  },
  tableHeader: {
    flex: 1,
    textAlign: 'center',
    fontSize: 13,
    color: '#888',
    fontWeight: '600',
  },
  tableCell: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    color: '#232526',
    fontWeight: '600',
  },
  tableCellInput: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cellInput: {
    width: 50,
    height: 36,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    textAlign: 'center',
    fontSize: 16,
    color: '#232526',
    fontWeight: '500',
    backgroundColor: 'transparent',
  },
  cellUnit: {
    fontSize: 14,
    color: '#888',
    marginLeft: 2,
  },
  finishButton: {
    backgroundColor: '#232526',
    borderRadius: 28,
    paddingVertical: 14,
    paddingHorizontal: 40,
    marginTop: 24,
    alignItems: 'center',
    width: '80%',
    alignSelf: 'center',
  },
  finishButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});

export default styles;
