import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  header: {
    width: '100%',
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: '#232526',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: 18,
    top: 50,
    zIndex: 10,
  },
  headerTitle: {
    fontSize: 32,
    color: '#fff',
    fontWeight: 'bold',
    letterSpacing: 1,
    textAlign: 'center',
  },
  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 22,
    marginHorizontal: 18,
    paddingVertical: 16,
    paddingHorizontal: 10,
    width: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    elevation: 4,
  },
  summaryItem: {
    flex: 1,
    alignItems: 'center',
  },
  summaryLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  summaryLabel: {
    fontSize: 13,
    color: '#888',
    fontWeight: '500',
    marginLeft: 4,
    textAlign: 'center',
  },
  summaryValue: {
    fontSize: 17,
    color: '#232526',
    fontWeight: 'bold',
    marginTop: 2,
    textAlign: 'center',
  },
  summaryDivider: {
    width: 1,
    height: 38,
    backgroundColor: '#e0e0e0',
  },
  exerciseCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginTop: 18,
    width: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    elevation: 4,
    alignSelf: 'center',
  },
  exerciseName: {
    fontSize: 22,
    fontWeight: '600',
    color: '#232526',
    textAlign: 'center',
    marginBottom: 8,
  },
  exerciseDivider: {
    height: 2,
    backgroundColor: '#e0e0e0',
    width: '100%',
    marginBottom: 10,
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 8,
    borderBottomWidth: 0,
  },
  tableHeader: {
    flex: 1,
    textAlign: 'center',
    fontSize: 14,
    color: '#888',
    fontWeight: '600',
  },
  tableCell: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    color: '#232526',
    fontWeight: '500',
  },
});

export default styles;
